### ISSUE TITLE
New in-order Event type

### ISSUE THREAD

**Issue by BartoszDunajski** [oneapi-src/level-zero-spec#145]
As continuation of discussion about #81, we decided that new Event type for in-order command list mode is required.

Requirements (open to discuss):
- In-order CL design assumes internal storage to track implicit dependencies. This is incremental counter
- Event inherits that value from CL during append API call
- New Event flag is required to create such Event
- New type can be signaled only from in-order CL
- Reset of that Event is forbidden
- Should we disallow host signaling too? 
- Timestamp mode is still allowed
- Event can be reused multiple times without reset. New API call overrides previous state (counter to wait)
- Wait call (GPU/CPU) on reused Event waits only for latest saved counter value
- Event can be reused on different command lists. Wait call (GPU/CPU) waits only for latest used CL and assigned counter value

**Comment by MichalMrozek** [comment]
Countered events doesn't make sense for out of order command lists, so I agree requirement should be to have it only for in order command lists.

"
Should we disallow host signaling too?
"

Yes host signaling would not possible and must be disallowed.

One more point, we need to clearly define what happens for non immediate command lists.
One option is to disallow those events in those scenario.
Another option is to allow them, but with clear semantic how they can be reused and how latests state is reflected, as it will not happen on append anymore due to recording.

**Comment by MichalMrozek** [comment]
We would need additional flag that would specify that countered events can be used on recorded command lists.
There will be additional handling needed in such scenarios and we do not want applications to pay it if they only want to use those countered events on immediate command lists.

**Comment by jandres742** [comment]
@MichalMrozek , @BartoszDunajski : please check https://github.com/oneapi-src/level-zero-spec/pull/221

**Comment by BartoszDunajski** [comment]
> We would need additional flag that would specify that countered events can be used on recorded command lists. There will be additional handling needed in such scenarios and we do not want applications to pay it if they only want to use those countered events on immediate command lists.

Should we make those flags mutually exclusive? For example event generated on non-immediate cmd lists cannot be used on immediate?

**Comment by MichalMrozek** [comment]
Right now user can represent if it wants:
- event for immediate command list 
- event for non immedaite command lists
- event for both immediate and non immediate command list

So I don't think we need to make them mutually exclusive.
