### ISSUE TITLE
add an extension to query device IP version

### ISSUE THREAD

**Issue by bashbaug** [oneapi-src/level-zero-spec#15]
We need to add a query for the "device IP version".  This would be a simple addition to zeDeviceGetProperties, and could be added in a similar way as the device LUID extension.

Is there anything else we should add to the same extension while we're at it?

See: https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_device_attribute_query.html

Notes:
* We already have the device ID via ze_device_properties_t.deviceId.
* We already have the number of slices via ze_device_properties_t.numSlices.
* We already have the number of sub-slices per slice via ze_device_properties_t.numSubslicesPerSlice.
* We already have the number of EUs per sub-slice via ze_device_properties_t.numEUsPerSubslice.
* We already have the number of threads per EU via ze_device_properties_t.numThreadsPerEU.
* We already have the dp4a feature flag via ze_device_module_flags_t.ZE_DEVICE_MODULE_FLAG_DP4A.
* We don't appear to have a feature flag for dpas.

**Comment by petercad** [comment]
@bashbaug Who's in charge of specifying the result of the device IP version query for Intel GPUs?
 (I'm assuming that wouldn't be part of the L0 spec.)

**Comment by jandres742** [comment]
@bashbaug 
from the opencl:

<html>
<body>


CL_DEVICE_IP_VERSION_INTEL | cl_version | The IP version for the device. The meaning of this version is implementation-defined, but newer devices should have a higher version than older devices.
-- | -- | --



</body>
</html>

so that's kind of vague. What is the actual meaning of this? or is just that we want to have L0 returning a similar number as OCL?
