### ISSUE TITLE
Clarification on pString in zeKernelGetSourceAttributes 

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/level-zero-spec#32]
For zeKernelGetSourceAttributes we have pString as forbidden to be passed as null:

ZE_APIEXPORT [ze_result_t](https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=zekernelgetsourceattributes#_CPPv411ze_result_t) ZE_APICALL zeKernelGetSourceAttributes(ze_kernel_handle_t hKernel, uint32_t *pSize, char **pString)

[ZE_RESULT_ERROR_INVALID_NULL_POINTER](https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=zekernelgetsourceattributes#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767a90dc7f955a711ba2377da3125672400f)

nullptr == pSize

nullptr == pString

However, what we usually do in this kind of interfaces is that the user first requests for pSize, then allocates the array's memory (in this case pString), and then in a second call passes that array to the driver, so the driver can copy the requested data.

@bashbaug : is my understanding correct, or is this a special case where the lifetime of the array is managed by the driver. That seems to be implied by this statement:

pString – [in,out] pointer to null-terminated string, whose lifetime is tied to the kernel object, where kernel source attributes are separated by space.

if so, shouldn't be pString just a pointer, instead of a double pointer?

**Comment by bashbaug** [comment]
Hmm, originally I thought this was clearly a bug, but now I'm not so sure, because of this line in the spec (**emphasis** mine):

> pString – [in,out] pointer to null-terminated string, **whose lifetime is tied to the kernel object**, where kernel source attributes are separated by space.

Is the expectation that this API should directly return a pointer to a driver string?  If so, it would make sense that this pointer should never be NULL, although it should definitely be const, which it is not currently, and the size in bytes isn't necessarily interesting:

```c
uint32_t size = 0;
char* str = nullptr;
zeKernelGetSourceAttributes(my_kernel, &size, &str);

printf("Size = %u, Source attributes = %s\n", size, str);
```

If the expectation is that this API should copy into an application-allocated string instead, though, then it is certainly valid that the string could be NULL, and it's questionable that the last argument should be a pointer-to-pointer-to-char.:

```c
uint32_t size = 0;
zeKernelGetSourceAttributes(my_kernel, &size, nullptr);

std::vector<char> str(size);
zeKernelGetSourceAttributes(my_kernel, &size, &str.data()); // why not just str.data()?

printf("Size = %u, Source attributes = %s\n", size, str.data());
```

Which of these is it?

(Aside: when are there attributes to return, given than we do not support creating modules or kernels from source strings?)

**Comment by wdamon-intel** [comment]
The implementation supports a NULL pString, so the latter code snippet in the above comment is the expected usage (i.e. first call the API with `nullptr` for the pString to obtain a meaningful `size`, then use that to allocate application memory for the driver to copy the string data into). We will update the spec language to clarify.

Changing the parameter type would require us add a new API, deprecate the existing API and tag it for removal in a future release.

**Comment by aelovikov-intel** [comment]
What about verification layer? Was it changed to allow the NULL pString?

**Comment by jandres742** [comment]
@aelovikov-intel thanks. Validation layer is automatically generated based on the scripts, which is what @wdamon-intel changed in #67, so on the next time the loader absorbs the generated headers, validation layer will have the new behavior.
