### ISSUE TITLE
Level0 APi which would return a string given ze_result_t error code

### ISSUE THREAD

**Issue by RaviNarayanaswamy** [oneapi-src/level-zero-spec#61]
We would like to print a meaningful error when level returns an error code
eg:- 

```cpp
ze_result_t ret = zeCommandListAppendLaunchKernel()
if (ret != ZE_RESULT_SUCCESS) {
    zeDriverGetErrorString(&str);
    printf("Error returned by L0: %s\n", str);
}
```

Currently we need to do this
```
  export PrintDebugMessages=1
  export NEOReadDebugKeys=1
```

**Comment by jandres742** [comment]
@zackwaters , @wdamon-intel : what do you think about this?

**Comment by wdamon-intel** [comment]
> [ZW, WD] what do you think about this?

I'm not opposed to idea, but it should be an SDK enhancement over a Core API feature.

**Comment by kevin-harms** [comment]
Why wouldn't it be added to the Core API?

**Comment by zackwaters** [comment]
I don't have any objection to this being added to the Core API.

**Comment by jandres742** [comment]
@wdamon-intel : could you elaborate on your suggestion above?

**Comment by wdamon-intel** [comment]
Basically, when I read this request, I saw an immediate parallel to the `vk_enum_string_helper.h` that is part of the Vulkan SDK. Certainly this would be a useful developer/debug tool, but does it merit a Core API?

That was my thinking... I'm not strictly opposed to it being a part of the Core API, however.

**Comment by jandres742** [comment]
thanks @wdamon-intel .
So use case here is that when doing something, like appending a kernel, L0 implementation finds there's a problem, for instance, SLM size is not enough. L0 driver would then return an error, maybe ZE_RESULT_ERROR_INVALID_ARGUMENT. However, that's not descriptive enough for the application to know what happened. With the interface suggested here, additional information could be returned.

Now, another solution of course would be to add a new error code for that, like in the example I mentioned above, we could have ZE_RESULT_ERROR_SLM_SIZE, or something similar. This means L0 spec would need to define more codes, which also seems to be the approach taken by Vulkan based on what is in https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/vk_enum_string_helper.h, since there's a lot of  error codes there :)

So we have I think two options:

1. Add errors codes to cover any new and possible scenario that could cause an L0 call to fail.
or
2. Add an interface like the one suggested here so if an L0 error code is not descriptive enough (or even if there's one close), the L0 driver implementation can return an expanded message to help applications and developers understand cause of error.

These may not be mutually exclusively, and regardless of what we decide with this new interface, we should continue adding new codes if it is found that none of the currently ones defined is explicit enough for a given failure.

**Comment by jandres742** [comment]
we could have something like

```cpp
///////////////////////////////////////////////////////////////////////////////
/// @brief Retrieves text string for last error returned by driver implementation
/// 
/// @details
///     - The caller can pass nullptr for pErrorString when querying only for size.
///     - The caller must provide memory for pErrorString.
///     - The application may call this function from simultaneous threads.
///     - The implementation of this function must be thread-safe.
/// 
/// @returns
///     - ::ZE_RESULT_SUCCESS
///     - ::ZE_RESULT_ERROR_UNINITIALIZED
///     - ::ZE_RESULT_ERROR_DEVICE_LOST
///     - ::ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY
///     - ::ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY
///     - ::ZE_RESULT_ERROR_INVALID_NULL_HANDLE
///         + `nullptr == hDriver`
///     - ::ZE_RESULT_ERROR_INVALID_NULL_POINTER
///         + `nullptr == pSize`
ZE_APIEXPORT ze_result_t ZE_APICALL
zeDriverGetErrorString(
    ze_driver_handle_t hDriver,            ///< [in] handle of the driver instance
    size_t* pSize,                                  ///< [in,out] size of error string.
    char* pErrorString                         ///< [in,out][optional] pointer to null-terminated error.
    );
```

**Comment by jandres742** [comment]
comments from meeting with @zackwaters and @wdamon-intel : this should be thread-local. I will be posting a proposal.
